# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin  : "sunrise"  # "air", "contrast", "aqua", "mint", "dark", "dirt", "neon", "plum"

# Site Settings
locale                   : "en-US"
title                    : "Wei Jin (金威)"
title_separator          : "-"
name                     : &name "Wei Jin (金威)"
description              : &description "Assistant Professor at the School of Economics, Nankai University. Research fields: International Economics, International Trade, and International Business."
url                      : "https://weijinsite.github.io"
baseurl                  : ""
repository               : "weijinsite/weijinsite.github.io"
teaser                   :
logo                     : "/images/smalltitle.png"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               :
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            : 100
    colorscheme          :

staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"

atom_feed:
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :

# For specifying social profiles
social:
  type                   : "Person"
  name                   : "Wei Jin"
  links:
    - "https://weijinsite.github.io"

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          :

# Site Author
author:
  name             : "Wei Jin (金威)"
  avatar           : "profile.png"
  bio              : "Assistant Professor, School of Economics, Nankai University"
  location         : "Tianjin, China"
  location_url     : "https://www.google.com/maps/search/?api=1&query=School+of+Economics%2C+Nankai+University%2C+No.+94+Weijin+Road%2C+Nankai+District%2C+Tianjin+300071%2C+China"
  employer         : "Nankai University"
  email            : "wei.jin.economics@gmail.com"
  uri              : "https://weijinsite.github.io"
  github           : "weijinsite"
  googlescholar    :
  pubmed           :
  researchgate     :
  google_plus      :
  impactstory      :
  linkedin         :
  orcid            :
  stackoverflow    :
  twitter          :
  youtube          :
  wikipedia        :

# Contact Information
contact:
  email_primary     : "wei.jin.economics@gmail.com"
  email_secondary   : "wei.jin.economics@foxmail.com"
  email_nankai      : "wei.jin@nankai.edu.cn"
  address           : "School of Economics, Nankai University, No. 94 Weijin Road, Nankai District, Tianjin 300071, P.R. China"

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  papers:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _papers
  - scope:
      path: ""
      type: papers
    values:
      layout: single
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Theme toggle
toggle:
  theme: true
